AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack to Deploy all of Antiope


Parameters:

  pBucketName:
    Description: Name of the Antiope Bucket to hold all the data
    Type: String
    Default: TO BE DEFINED BY MAKEFILE

  pAWSRoleName:
    Description: Default name of the AssumeRole to assume into accounts
    Type: String
    Default: Security-Audit

  pIamUserName:
    Type: String
    Description: <optional> IAM Username with access to the Inventory Bucket
    Default: NONE

  pExecutionRate:
    Description: How frequently the StepFunction should Run (As a CloudWatch ScheduleExpression)
    Type: String
    Default: rate(1 hour)

  pStaggerAccelerationFactor:
    Description: Factor by which the delay between SNS Publish is shrunk. The larger the number, the more frequent the publish.
    Type: Number
    Default: 2

  pAWSEntSupport:
    Type: String
    Description: Set this to True if you have Business or Enterprise Support and can access support API
    Default: False
    AllowedValues:
      - True
      - False

  pAWSEBSInventory:
    Type: String
    Description: Set this to True if you want Inventory EBS and Snapshots
    Default: False
    AllowedValues:
      - True
      - False

  pDeployElasticSearch:
    Type: String
    Description: Deploy the Elastic Search Cluster component of Antiope
    Default: False
    AllowedValues:
      - True
      - False

  pClusterEncryption:
    Type: String
    Description: Enable Encryption for the Elasticsearch Cluster
    Default: False
    AllowedValues:
      - True
      - False

  pAWSLambdaLayerPackage:
    Description: AWS Inventory Lambda Layer Package Object Key
    Type: String
    Default: TO BE DEFINED BY MAKEFILE

  pClusterInstanceType:
    Type: String
    Description: Size of the ES Cluster
    Default: t2.small.elasticsearch
    ConstraintDescription: Must be a valid Elasticsearch Service InstanceType (https://aws.amazon.com/elasticsearch-service/pricing/)

  pClusterInstanceCount:
    Type: Number
    Description: Cluster Instance Count
    Default: 1

  pClusterEncryption:
    Type: String
    Description: Enable Encryption for the Elasticsearch Cluster
    Default: False
    AllowedValues:
      - True
      - False

  pElasticSearchDomainName:
    Description: Name of the Elasticsearch Domain (leave blank to match Antiope Stack Name)
    Type: String
    MaxLength: 28
    Default: BLANK

  pEmailAddress:
    Type: String
    Description: Default Username for Cognito
    Default: NONE

  pIdentityPoolName:
    Type: String
    Description: Name of the Identity Pool. Cannot contain non-alphanumeric char
    Default: AntiopeIDPool
    ConstraintDescription: pIdentityPoolName must only contain uppercase and lowercase letters and numbers
    AllowedPattern: "[A-Za-z0-9]+"

  pCustomCognitoDomain:
    Description: What you will modify the User pool after it is created (Can't be done via CFT)
    Type: String
    Default: antiope

  pCustomAPIDomain:
    Description: The Custom Domain Name you will configure once the API Gateway is created
    Type: String



Conditions:
  cDeployElasticSearch: !Equals [ !Ref pDeployElasticSearch, True]
  cCreateIAMUser: !Not [ !Equals [ !Ref pIamUserName, "NONE"] ]


Resources:

  InventoryIAMUser:
    Condition: cCreateIAMUser
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref pIamUserName
      Path: /
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:*
            Effect: Allow
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref pBucketName , /*]]
              - !Join ['', ['arn:aws:s3:::', !Ref pBucketName ]]
          - Action:
            - s3:ListAllMyBuckets
            - s3:GetBucketLocation
            Effect: Allow
            Resource: '*'

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pBucketName: !Ref pBucketName
        pCustomAPIDomain: !Ref pCustomAPIDomain
        pCustomCognitoDomain: !Ref pCustomCognitoDomain
        pEmailAddress: !Ref pEmailAddress
        pIdentityPoolName: !Ref pIdentityPoolName
      TemplateURL: ../cognito/cloudformation/Cognito-Template.yaml
      TimeoutInMinutes: 30

  AWSInventoryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
          pAWSLambdaLayerPackage: !Ref pAWSLambdaLayerPackage
          pBucketName: !Ref pBucketName
          pEBSInventory: !Ref pAWSEBSInventory
          pEntSupport: !Ref pAWSEntSupport
          pExecutionRate: !Ref pExecutionRate
          pRoleName: !Ref pAWSRoleName
          pStaggerAccelerationFactor: !Ref pStaggerAccelerationFactor
          pResourcePrefix: !Sub "${AWS::StackName}-aws-inventory"
      TemplateURL: ../aws-inventory/cloudformation/Inventory-Template.yaml
      TimeoutInMinutes: 30

  ElasticSearchStack:
    Type: AWS::CloudFormation::Stack
    Condition: cDeployElasticSearch
    Properties:
      Parameters:
          pAWSLambdaLayerPackage: !Ref pAWSLambdaLayerPackage
          pBucketName: !Ref pBucketName
          pClusterEncryption: !Ref pClusterEncryption
          pClusterInstanceCount: !Ref pClusterInstanceCount
          pClusterInstanceType: !Ref pClusterInstanceType
          pCognitoKibanaAuthRole: !GetAtt CognitoStack.Outputs.CognitoKibanaAuthRole
          pDomainName: !Ref pElasticSearchDomainName
          pResourcePrefix: !Sub "${AWS::StackName}-search-cluster"
      TemplateURL: ../search-cluster/cloudformation/SearchCluster-Template.yaml
      TimeoutInMinutes: 30


Outputs:
  StackName:
    Value: !Ref AWS::StackName
    Description: Just the name of this stack

  BucketName:
    Value: !Ref pBucketName
    Description: Name of S3 Bucket where all files are stored

  AWSInventoryTriggerTopic:
    Value: !GetAtt AWSInventoryStack.Outputs.InventoryTriggerTopic
    Description: Topic that triggers the per-account inventory lambda. You can subscribe custom lambda to this topic

  AWSNewAccountNotificationTopic:
    Value: !GetAtt AWSInventoryStack.Outputs.NewAccountNotificationTopic
    Description: The discovery of new accounts is sent to this topic.

  AWSForeignAccountNotificationTopic:
    Value: !GetAtt AWSInventoryStack.Outputs.ForeignAccountNotificationTopic
    Description: The discovery of new foreign (ie discovered in AMI or AssumeRole Policies) are sent to this topic

  AWSTriggerEventName:
    Value: !GetAtt AWSInventoryStack.Outputs.TriggerEventName
    Description: Name of the Trigger Event (used by the make file to enable to disable the inventory state machine)

  LoginUrl:
    Description: Login URL for Cognito
    Value: !GetAtt CognitoStack.Outputs.LoginUrl

  ClusterEndpoint:
    Condition: cDeployElasticSearch
    Description: DNS Name for the Elastic Search Cluster
    Value: !GetAtt ElasticSearchStack.Outputs.ClusterEndpoint

  KibanaURL:
    Condition: cDeployElasticSearch
    Description: "The URL to access Kibana."
    Value: !GetAtt ElasticSearchStack.Outputs.KibanaURL

  SearchIngestEventQueueArn:
    Condition: cDeployElasticSearch
    Description: Arn of the SQS Queue S3 should send new events notifications to
    Value: !GetAtt ElasticSearchStack.Outputs.SearchIngestEventQueueArn

  SearchIngestEventQueueUrl:
    Condition: cDeployElasticSearch
    Description: Arn of the SQS Queue S3 should send new events notifications to
    Value: !GetAtt ElasticSearchStack.Outputs.SearchIngestEventQueueUrl




  AWSErrorQueue:
    Description: Name of the SQS Queue where lambda errors are sent
    Value: !GetAtt AWSInventoryStack.Outputs.ErrorQueue

